# Generated by Django 4.2.14 on 2024-09-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='javascriptsnippet',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
